module.exports = {
    EarthIcon: require('./earth').default,
    BasketballIcon: require('./basketball').default,
    AwardIcon: require('./award').default,
    FacebookIcon: require('./facebook').default,
    TwitterIcon: require('./twitter').default,
    YouTubeIcon: require('./youtube').default,
    LocationStartIcon: require('./location-start').default,
    LocationMiddleIcon: require('./location-middle').default,
    LocationEndIcon: require('./location-end').default,
    LevelEasyIcon: require('./level-easy').default,
    LevelModerateIcon: require('./level-moderate').default,
    LevelAdvanceIcon: require('./level-advance').default,
    PeopleJoinedIcon: require('./people-joined').default,
    TimeIcon: require('./time').default,
    TimeSandIcon: require('./time-sand').default,
    FoodVariantIcon: require('./food-variant').default,
    DrinksIcon: require('./drinks').default,
    FilePdfIcon: require('./file-pdf').default,
    SunIcon: require('./sun').default,
    PlusIcon: require('./plus').default,
    MinusIcon: require('./minus').default,

};
